<?php

/* 
function makeTree(array $item)
{

}
*/


// Returns a tree structure with children grouped by parent_id
function tree(array $items, int $parent_id = 0, int $level = 1) : array {
    $branch = [];
    foreach ($items as $item) {
        if ($item['parent_id'] == $parent_id) {
            $item['level'] = $level;
            $children = tree($items, $item['id'], $level + 1);
            if ($children) {
                $item['children'] = $children;
            }
            $branch[] = $item;
        }
    }
    return $branch;
}

// Flatten a tree generated by the tree function
function flatten(array $tree) : array {
    $result = [];
    foreach ($tree as $node) {
        $children = $node['children'] ?? false;
        if ($children) {
            unset($node['children']);
            $result[] = $node;
            $result = array_merge($result, flatten($children));
        } else {
            $result[] = $node;
        }
    }
    return $result;
}
